name = "snapit"
compatibility_date = "2026-06-03"
pages_build_output_dir = "./dist"

[vars]
VITE_API_URL = "https://snapit-api-production.up.railway.app"
VITE_RAZORPAY_KEY_ID = "rzp_live_Sm766x1DQg2bij"
VITE_FIREBASE_API_KEY= "AIzaSyAn7lwvs2e4x1vkHN3aqpZL1cwF5_LCFrE"
VITE_FIREBASE_AUTH_DOMAIN= "snapit-da080.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID= "snapit-da080"
VITE_FIREBASE_STORAGE_BUCKET= "snapit-da080.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID= "404894201207"
VITE_FIREBASE_APP_ID= "1:404894201207:web:1603b3e3dc46f65f4e9d72"
VITE_FIREBASE_MEASUREMENT_ID= "G-MHJZV49XNS"
VITE_FIREBASE_VAPID_KEY= "BL_FzqJGuSIYUsMzNo6ZUTjAQSW7IDgcAdumxCwjHFSGa_XJRiubBJa-hvFgdiCE8VcfnPIobc6IDFSlqMzvvak"